#!/bin/sh

MSG=$1
LINE_COUNT=`echo "$MSG" | wc -l`

FONT="-*-terminus-medium-r-*-*-16-*-*-*-*-*-*-*"
BG="#ffffff"
FG="#224488"
DELAY=10
X=1600
Y=20
WIDTH=300

echo $1 | dzen2 -l `expr $LINE_COUNT - 1` -x $X -y $Y -w $WIDTH -fn $FONT -bg $BG -fg $FG -ta l -sa l -e 'onstart=uncollapse;button1=exit' -p $DELAY
